package com.etpms.dao;
import com.etpms.util.DB;import com.etpms.util.Passwords;import java.sql.*;import java.util.*;
public class AdminDAO{
 public List<Map<String,Object>> employees()throws SQLException{String sql="SELECT e.id,e.first_name,e.last_name,e.email,e.job_title,e.department_id,d.name department,u.username,u.role FROM employees e JOIN users u ON u.id=e.user_id LEFT JOIN departments d ON d.id=e.department_id ORDER BY e.first_name";try(Connection c=DB.get();Statement s=c.createStatement();ResultSet r=s.executeQuery(sql)){List<Map<String,Object>> a=new ArrayList<>();while(r.next()){Map<String,Object> m=new LinkedHashMap<>();for(String k:new String[]{"id","first_name","last_name","email","job_title","department_id","department","username","role"})m.put(k,r.getObject(k));a.add(m);}return a;}}
 public List<Map<String,Object>> departments()throws SQLException{try(Connection c=DB.get();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT d.id,d.name,d.description,COUNT(e.id) employee_count FROM departments d LEFT JOIN employees e ON e.department_id=d.id GROUP BY d.id ORDER BY d.name")){List<Map<String,Object>> a=new ArrayList<>();while(r.next()){Map<String,Object> m=new LinkedHashMap<>();for(String k:new String[]{"id","name","description","employee_count"})m.put(k,r.getObject(k));a.add(m);}return a;}}
 public void createEmployee(String username,String password,String role,String first,String last,String email,String job,String department)throws SQLException{if(username==null||!username.matches("[A-Za-z0-9._-]{3,60}")||password==null||password.length()<5||first==null||first.isBlank()||last==null||last.isBlank()||email==null||!email.matches("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$"))throw new IllegalArgumentException("Use a 3–60 character username, a password with at least 5 characters, and valid name and email fields.");if(!Set.of("MANAGER","EMPLOYEE").contains(role))throw new IllegalArgumentException("Choose Manager or Employee.");String salt=Passwords.salt();try(Connection c=DB.get()){c.setAutoCommit(false);try{long user;try(PreparedStatement p=c.prepareStatement("INSERT INTO users(username,password_hash,password_salt,role) VALUES(?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){p.setString(1,username.trim());p.setString(2,Passwords.hash(password,salt));p.setString(3,salt);p.setString(4,role);p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){r.next();user=r.getLong(1);}}try(PreparedStatement p=c.prepareStatement("INSERT INTO employees(user_id,department_id,first_name,last_name,email,job_title,manager_id) VALUES(?,?,?,?,?,?,?)")){p.setLong(1,user);if(department==null||department.isBlank())p.setNull(2,Types.BIGINT);else p.setLong(2,Long.parseLong(department));p.setString(3,first.trim());p.setString(4,last.trim());p.setString(5,email.trim());p.setString(6,job);if("EMPLOYEE".equals(role)){try(PreparedStatement m=c.prepareStatement("SELECT e.id FROM employees e JOIN users u ON u.id=e.user_id WHERE u.role='MANAGER' ORDER BY e.id LIMIT 1");ResultSet r=m.executeQuery()){if(r.next())p.setLong(7,r.getLong(1));else p.setNull(7,Types.BIGINT);}}else p.setNull(7,Types.BIGINT);p.executeUpdate();}c.commit();}catch(SQLException|RuntimeException e){c.rollback();throw e;}}}
 public void updateEmployee(long id,String first,String last,String email,String job,String department)throws SQLException{if(first==null||first.isBlank()||last==null||last.isBlank()||email==null||!email.matches("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$"))throw new IllegalArgumentException("Enter a valid name and email.");try(Connection c=DB.get();PreparedStatement p=c.prepareStatement("UPDATE employees SET first_name=?,last_name=?,email=?,job_title=?,department_id=? WHERE id=?")){p.setString(1,first.trim());p.setString(2,last.trim());p.setString(3,email.trim());p.setString(4,job);if(department==null||department.isBlank())p.setNull(5,Types.BIGINT);else p.setLong(5,Long.parseLong(department));p.setLong(6,id);if(p.executeUpdate()!=1)throw new SQLException("Employee not found.");}}
 public void deleteEmployee(long id)throws SQLException{try(Connection c=DB.get();PreparedStatement p=c.prepareStatement("DELETE FROM employees WHERE id=?")){p.setLong(1,id);if(p.executeUpdate()!=1)throw new SQLException("Employee not found.");}}
 public void createDepartment(String name,String description)throws SQLException{if(name==null||name.isBlank()||name.length()>100)throw new IllegalArgumentException("Enter a department name (100 characters max).");try(Connection c=DB.get();PreparedStatement p=c.prepareStatement("INSERT INTO departments(name,description) VALUES(?,?)")){p.setString(1,name.trim());p.setString(2,description);p.executeUpdate();}}
 public void deleteDepartment(long id)throws SQLException{try(Connection c=DB.get();PreparedStatement p=c.prepareStatement("DELETE FROM departments WHERE id=?")){p.setLong(1,id);if(p.executeUpdate()!=1)throw new SQLException("Department not found.");}}
}
