package com.etpms.dao;
import com.etpms.model.User;import com.etpms.util.DB;import java.sql.*;import java.util.ArrayList;import java.util.LinkedHashMap;import java.util.List;import java.util.Map;
public class TaskDAO {
 public List<Map<String,Object>> list(User u)throws SQLException{String q="SELECT t.*,e.first_name,e.last_name FROM tasks t JOIN employees e ON e.id=t.assigned_to";if("EMPLOYEE".equals(u.role))q+=" JOIN users x ON x.id=e.user_id WHERE x.id=?";else if("MANAGER".equals(u.role))q+=" JOIN users x ON x.id=e.user_id JOIN employees me ON me.user_id=? WHERE e.manager_id=me.id";q+=" ORDER BY t.due_date";try(Connection c=DB.get();PreparedStatement p=c.prepareStatement(q)){if(!"ADMIN".equals(u.role))p.setLong(1,u.id);try(ResultSet r=p.executeQuery()){List<Map<String,Object>> out=new ArrayList<>();while(r.next()){Map<String,Object> m=new LinkedHashMap<>();for(String k:new String[]{"id","title","description","priority","status","start_date","due_date","first_name","last_name"})m.put(k,r.getObject(k));out.add(m);}return out;}}}
 public Map<String,Integer> stats(User u)throws SQLException{Map<String,Integer> m=new LinkedHashMap<>();m.put("total",0);m.put("completed",0);m.put("pending",0);m.put("inProgress",0);m.put("overdue",0);String q="SELECT COUNT(*) total,SUM(status='COMPLETED') completed,SUM(status='PENDING') pending,SUM(status='IN_PROGRESS') progress,SUM(status<>'COMPLETED' AND due_date<CURRENT_DATE) overdue FROM tasks";if("EMPLOYEE".equals(u.role))q+=" JOIN employees e ON e.id=tasks.assigned_to JOIN users x ON x.id=e.user_id WHERE x.id=?";else if("MANAGER".equals(u.role))q+=" JOIN employees e ON e.id=tasks.assigned_to JOIN employees me ON me.user_id=? WHERE e.manager_id=me.id";try(Connection c=DB.get();PreparedStatement p=c.prepareStatement(q)){if(!"ADMIN".equals(u.role))p.setLong(1,u.id);try(ResultSet r=p.executeQuery()){if(r.next()){m.put("total",r.getInt("total"));m.put("completed",r.getInt("completed"));m.put("pending",r.getInt("pending"));m.put("inProgress",r.getInt("progress"));m.put("overdue",r.getInt("overdue"));}}}return m;}
 public void updateStatus(long id,String status,long userId,String role)throws SQLException{if(!List.of("PENDING","IN_PROGRESS","COMPLETED").contains(status))throw new IllegalArgumentException("Invalid status");String q="UPDATE tasks t SET status=? WHERE id=?"+("ADMIN".equals(role)?"":" AND assigned_to IN (SELECT e.id FROM employees e WHERE e.user_id=? OR e.manager_id=(SELECT id FROM employees WHERE user_id=?))");try(Connection c=DB.get();PreparedStatement p=c.prepareStatement(q)){p.setString(1,status);p.setLong(2,id);if(!"ADMIN".equals(role)){p.setLong(3,userId);p.setLong(4,userId);}if(p.executeUpdate()!=1)throw new SQLException("Task not found or access denied");}}
 public void create(String title,String desc,String priority,String start,String due,long creator,long assignee,String role)throws SQLException{try(Connection c=DB.get()){if("MANAGER".equals(role)){try(PreparedStatement check=c.prepareStatement("SELECT 1 FROM employees a JOIN employees m ON m.id=a.manager_id WHERE a.id=? AND m.user_id=?")){check.setLong(1,assignee);check.setLong(2,creator);try(ResultSet r=check.executeQuery()){if(!r.next())throw new SQLException("You can only assign tasks to employees who report to you.");}}}String q="INSERT INTO tasks(title,description,priority,start_date,due_date,created_by,assigned_to) VALUES(?,?,?,?,?,?,?)";try(PreparedStatement p=c.prepareStatement(q)){p.setString(1,title);p.setString(2,desc);p.setString(3,priority);p.setDate(4,Date.valueOf(start));p.setDate(5,Date.valueOf(due));p.setLong(6,creator);p.setLong(7,assignee);p.executeUpdate();}}}
 public List<Map<String,Object>> employees()throws SQLException{try(Connection c=DB.get();PreparedStatement p=c.prepareStatement("SELECT e.id,e.first_name,e.last_name,e.email,e.job_title,d.name department,u.username,u.role FROM employees e JOIN users u ON u.id=e.user_id LEFT JOIN departments d ON d.id=e.department_id ORDER BY e.first_name");ResultSet r=p.executeQuery()){List<Map<String,Object>> out=new ArrayList<>();while(r.next()){Map<String,Object> m=new LinkedHashMap<>();for(String k:new String[]{"id","first_name","last_name","email","job_title","department","username","role"})m.put(k,r.getObject(k));out.add(m);}return out;}}
}
